# Generated by Django 3.1.3 on 2020-12-02 06:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_componente', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Componentes',
            },
        ),
        migrations.CreateModel(
            name='ComponenteNegocio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_componente_negocio', models.CharField(default=None, help_text='Descripción del Componente de Negocios', max_length=150, verbose_name='Descripción del componente de negocios')),
                ('descripcion_corta_componente_negocio', models.CharField(default=None, help_text='Descripción Corta del Componente de Negocios', max_length=50, verbose_name='Descripción Corta del componente de negocios')),
                ('tipo_componente_negocio', models.SmallIntegerField(choices=[(1, 'CORPORATIVO'), (2, 'DIVISIÓN'), (3, 'ÁREA'), (4, 'DEPARTAMENTO o SUCURSAL')], default=1, help_text='(1) Corporativo o (2) División (MexAba/Hotelería)', verbose_name='Tipo de Componente de Negocios')),
                ('codigo_componente_negocio', models.CharField(default=None, help_text='Código para identificar el Componente de Negocios', max_length=2, verbose_name='Código para identificar la Clasificación de la Organización')),
                ('slug', models.SlugField()),
                ('activo', models.BooleanField(default=True, help_text='Estado Lógico del Registro (Activo|Inactivo)', verbose_name='Activo')),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='item.componentenegocio', verbose_name='Depende de')),
            ],
            options={
                'verbose_name_plural': 'Componentes de Negocio',
                'ordering': ('codigo_componente_negocio', 'descripcion_corta_componente_negocio'),
            },
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_dispositivo', models.CharField(choices=[('PR', 'Periferico'), ('PC', 'CPU'), ('LT', 'LapTop')], default='CPU', max_length=40)),
                ('nombre_dispositivo', models.CharField(choices=[('TD', 'Teclado'), ('MS', 'Mouse'), ('MT', 'Monitor'), ('LC', 'Lectora'), ('PR', 'Impresora'), ('MP', 'Miniprinter'), ('PC', 'CPU'), ('LT', 'LapTop')], default='CPU', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Dispositivos',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_id', models.CharField(max_length=30)),
                ('fabricante', models.CharField(max_length=45)),
                ('marca', models.CharField(max_length=45)),
                ('modelo', models.CharField(max_length=45)),
                ('capacidad', models.CharField(max_length=45)),
                ('serie', models.CharField(max_length=45)),
                ('entradas', models.CharField(max_length=45)),
                ('slug', models.SlugField()),
                ('desc', models.TextField(default='Sin observaciones')),
                ('componente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.componente')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.dispositivo')),
            ],
            options={
                'verbose_name_plural': 'Items-Componentes',
            },
        ),
        migrations.CreateModel(
            name='NivelDeConfidencialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_nivel_confidencialidad', models.CharField(default=None, help_text='Descripción del Nivel de Confidencialidad', max_length=50, verbose_name='Descripción del Nivel de Confidencialidad')),
                ('nivel_confidencialidad', models.IntegerField(default=0, help_text='100 - Mayor de Nivel de Acceso, 0 - Nulo nivel de acceso', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Nivel de Confidencialidad')),
                ('activo', models.BooleanField(default=True, help_text='Estado Lógico del Registro (Activo/Inactivo)', verbose_name='Activo')),
            ],
            options={
                'verbose_name_plural': 'Niveles de Confidencialidad',
                'ordering': ('nivel_confidencialidad', 'descripcion_nivel_confidencialidad'),
            },
        ),
        migrations.CreateModel(
            name='PerfilDePuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_perfil_puesto', models.CharField(default='DIRECTOR', help_text='Descripción del Perfil de Puesto', max_length=150, verbose_name='Descripción del Nivel de Confidencialidad')),
                ('codigo_perfil_puesto', models.CharField(default=None, help_text='Código para identificar el Perfil de Puesto', max_length=2, verbose_name='Código para identificar el Perfil del Puesto')),
                ('activo', models.BooleanField(default=True, help_text='Estado Lógico del Registro (Activo|Inactivo)', verbose_name='Activo')),
                ('nivel_confidencialidad_default', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.niveldeconfidencialidad')),
            ],
            options={
                'verbose_name_plural': 'Perfiles de Puestos',
                'ordering': ('codigo_perfil_puesto', 'descripcion_perfil_puesto'),
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=None, help_text='Nombre del Personal', max_length=100, verbose_name='Nombre de la persona')),
                ('apellido_paterno', models.CharField(default=None, help_text='Apellido Paterno', max_length=100, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(default='X', help_text='Apellido Materno', max_length=100, verbose_name='Apellido Materno')),
                ('activo', models.BooleanField(default=True, help_text='Estado Lógico del Registro (Activo|Inactivo)', verbose_name='Activo')),
                ('componente_negocio', models.ForeignKey(help_text='Componente (Depto., Área, Sucursal) de Negocio al que está asignado', on_delete=django.db.models.deletion.CASCADE, to='item.componentenegocio', verbose_name='Asignado a')),
                ('nivel_confidencialidad', models.ForeignKey(help_text='Nivel de Confidencialidad Asignado al Personal', on_delete=django.db.models.deletion.CASCADE, to='item.niveldeconfidencialidad', verbose_name='Nivel de Confidencialidad')),
                ('perfil_puesto', models.ForeignKey(help_text='Perfil de puesto del personal', on_delete=django.db.models.deletion.CASCADE, to='item.perfildepuesto', verbose_name='Perfil de Puesto')),
            ],
            options={
                'verbose_name_plural': 'Personal',
                'ordering': ('componente_negocio', 'perfil_puesto', 'nivel_confidencialidad', 'nombre', 'apellido_paterno', 'apellido_materno'),
            },
        ),
        migrations.CreateModel(
            name='PuestoTrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto_trabajo', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('fecha_fabricacion', models.DateField()),
                ('fecha_actual', models.DateField(auto_now_add=True)),
                ('tipo_sist', models.CharField(default='Sistema Operativo', max_length=30)),
                ('estado', models.CharField(choices=[('OK', 'Funcionando'), ('PF', 'ProximoFallo'), ('1F', 'Fallo')], default='Funcionando', max_length=45)),
                ('desc', models.TextField(default='Sin Observaciones')),
                ('activo1', models.BooleanField(default=True, help_text='Estado Lógico del Registro (Activo|Inactivo)', verbose_name='Activo')),
                ('ip_add', models.GenericIPAddressField(default='0.0.0.0', protocol='IPv4')),
                ('comp_neg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.componentenegocio')),
                ('items', models.ManyToManyField(to='item.Item')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.personal')),
            ],
            options={
                'verbose_name_plural': 'Equipos',
                'db_table': 'relacion_equipos_hardware',
                'ordering': ('comp_neg', 'responsable'),
            },
        ),
    ]
